### ISSUE TITLE
Support Installation of Kuadrant on OpenShift

### ISSUE THREAD

**Issue by maleck13** [Kuadrant/kuadrant-controller#108]
**Use Case**

As a cluster admin, I would like to install Kuadrant on to my OpenShift cluster so that I can provide my development teams with the tools needed to protect their services and APIs

**Options**

Provide an Operator available via the Operator Hub that can install the Kuadrant components onto a cluster that already has Isito installed.

**Demo**

- Show a cluster with Isito pre installed
- Show installing the operator
- Show configuring Kuadrant on the cluster to work with an existing Istio Gateway
- Show the kuadrant CRDS as available

**Done**

- [ ] Kuadrant Operator that can install the kuadrant components (Limitador, Kuadrant Controller, Authorino)
- [ ] Kuadrant CR that allows Kuadrant to be configured to use an existing Gateway (IE it doesn't have to create its own gateway)
- [ ] Authorino set up in Istio as a Auth GRPC service
- [ ] Document how to use the operator to do installation

**Comment by maleck13** [comment]
@mikenairn could you give an overview of the current state of the operator?
I believe it will setup limitador and authorino and set up their CRDS via OLM dependencies, but currently has no Kuadrant CRD for any additional setup needed

**Comment by mikenairn** [comment]
@maleck13 Yes, currently just installs the dependency operators(authorino, limitador) via OLM and deploys the controller. It currently has no reconciliation loop of it's own (kuadrant CR).
