### ISSUE TITLE
Implement the new design for AuthPolicy using Gateway API Policy attachment

### ISSUE THREAD

**Issue by maleck13** [Kuadrant/kuadrant-controller#155]
**What**

Based on the design outlined in https://github.com/Kuadrant/kuadrant-controller/issues/151, implement auth policy:

https://hackmd.io/GQAOxDRdQTudSlsWdhtiUg

**Demo**

- After Kuadrant is installed, I am able to create an AuthPolicy that protects all routes for the host specified by my HTTPRoute
- I am able to modify this policy to protect just the /admin/* routes and allow /public/* to not be authenticated
- When I delete the authpolicy, my HTTPRoute should no longer be protected. 

- [x] Move proposal to this repo
- [x] Define the types for AuthPolicy and embed AuthConfig
- [x] Refactor the AuthPolicy controller
- [x] Add unit tests
- [x] Add e2e test 
- [x] Add documentation and basic guides for getting started with the AuthPolicy

**Comment by maleck13** [comment]
@rahulanand16nov do you feel this is ready to implement?

**Comment by rahulanand16nov** [comment]
Yeah, just need to sketch up the status part but otherwise looks ready to me.

**Comment by rahulanand16nov** [comment]
Done :)
